### ISSUE TITLE
Let user know that app requires wifi/data

### ISSUE THREAD

**Issue by cgeroux** [katescarth/literary-halifax-mobile-app#8]
If I start the app up without wifi things don't look right, there should be a way to detect that the user doesn't have wifi/data connection and let them know, via pop message etc. that the app won't be fully functional without a data connection.

Will need to think a bit about differences between first time launch, and later launching it when data has already been cached as this message wouldn't be needed.

**Comment by cgeroux** [comment]
It might be good to detect when a connection has been established and reload content.

**Comment by David-Owen-Walker** [comment]
5c75b14a2b60a656681a3ed31a18e527586fd156 Displays a popup when the app starts with no connection (unless caching is on). Refreshing when the app comes online is introducing some odd bugs, so not comitted yet.

**Comment by David-Owen-Walker** [comment]
Related: d3e831ee57d94d336f85317a09e3577e5a542a7d displays a dummy map tile when there is no connection

**Comment by David-Owen-Walker** [comment]
de75ef5d8a2936ad0c3dc3f1bcbd98abe5341ff1 watches for a connection and refreshes when the app goes from offline to online. Closing.
